=== kambia777/migracion_tibco_java_v2.0/demo1/src/main/resources/testfile/input2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="clientes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="cliente">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id" type="xs:string" />
							<xs:element name="codigo" type="xs:string" />
							<xs:element name="pedido">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="fecha" type="xs:string" />
										<xs:element name="estado" type="xs:string" />
										<xs:element name="total" type="xs:string" />
										<xs:element name="detalle_pedido" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="producto">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="id_producto" type="xs:string" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="cantidad" type="xs:string" />
													<xs:element name="precio_unitario" type="xs:string" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== kambia777/migracion_tibco_java_v2.0/demo1/src/main/resources/testfile/input2.xml
<clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../xsd/input2.xsd">
<cliente>
	<id>2</id>
	<codigo>2</codigo>
	<pedido>
		<fecha>2024-12-12</fecha>
		<estado>confirmado</estado>
		<total>1.00</total>
		<detalle_pedido>
			<producto>
				<id_producto>6</id_producto>
			</producto>
			<cantidad>1</cantidad>
			<precio_unitario>1.00</precio_unitario>
		</detalle_pedido>
	</pedido>
</cliente>
<cliente>
	<id>3</id>
	<codigo>3</codigo>
	<pedido>
		<fecha>2024-12-12</fecha>
		<estado>confirmado</estado>
		<total>1.00</total>
		<detalle_pedido>
			<producto>
				<id_producto>7</id_producto>
			</producto>
			<cantidad>1</cantidad>
			<precio_unitario>1.00</precio_unitario>
		</detalle_pedido>
	</pedido>
</cliente>
</clientes>
